### ISSUE TITLE
OutFox support?

### ISSUE THREAD

**Issue by SheepyChris** [cesarmades/piunoteskins#3]
Since 5.2's development has been long time done, would it be possible to port these noteskins to Project OutFox? It follows the same system as 5.1 with a few improvements, I currently do have a couple of StepP1 noteskins ported over but they're not perfect and I'm not too familiar with how noteskins work in general.

**Comment by r3dthr33** [comment]
I guess everything is possible. However I'm not really into make it happen since I have been really inactive on the PIU community and with no intentions on coming back.

I remember Project OutFox being a fork of an early version of SM5, I don't know if they got to implement the new noteskin format (NewSkins). If they did then these NoteSkins should be compatible.

You can always fork this repo and do the port by yourself, if you're into coding it shouldn't take too much time to make a decent port (I'm not a coder myself). All the graphics work has been done already from the assets I got from Prime 1.
